language: c
os: linux
dist: trusty
sudo: false
git:
  submodules: true
script:
  - echo "Hi Travis"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git checkout master
  - git submodule update --recursive --remote
  - git add -A
  - git commit -a -m "Updated Gist Submodule Directory";echo $?;echo $?;
  - REPO=$(git remote get-url origin | sed -e "s/$GITHUB/$GITHUB_TOKEN@$GITHUB/g")
  - git push $REPO master
  - echo "Gist Submodule Fetch Done!"
